#!/bin/bash
# Copyright (c) 2011 Massachusetts Institute of Technology
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Load the doit system into the goby database.
# Must be run by a db user with admin priviledges.

DBNAME=$1
OUTFILE=init.out

psql $DBNAME -f core.sql &> $OUTFILE
psql $DBNAME -f util.sql >> $OUTFILE 2>&1
psql $DBNAME -f qgrams.sql >> $OUTFILE 2>&1
psql $DBNAME -f tokenize.sql >> $OUTFILE 2>&1

psql $DBNAME -f nameres/training.sql >> $OUTFILE 2>&1
psql $DBNAME -f nameres/name_resolve.sql >> $OUTFILE 2>&1
psql $DBNAME -f nameres/qgrams.sql >> $OUTFILE 2>&1
psql $DBNAME -f nameres/mdl.sql >> $OUTFILE 2>&1
psql $DBNAME -f nameres/ngrams.sql >> $OUTFILE 2>&1
psql $DBNAME -f nameres/dist.sql >> $OUTFILE 2>&1

# Attribute name factoring:
#psql $DBNAME -f factor/substrs.sql >> $OUTFILE 2>&1
#psql $DBNAME -f factor/factor.sql >> $OUTFILE 2>&1

# Old entity resolver for end-to-end demo:
psql $DBNAME -f entityres/old.sql >> $OUTFILE 2>&1

psql $DBNAME -f entityres/dedup_core.sql >> $OUTFILE 2>&1
psql $DBNAME -f entityres/general_learning_v1.sql >> $OUTFILE 2>&1
psql $DBNAME -f entityres/general_dedup_v1.sql >> $OUTFILE 2>&1

cat $OUTFILE | grep 'ERROR'

exit
